import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { useState } from 'react' 
import { Button } from '@mui/material'
import { TextField } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Intro />
      </main>
    </>
  )
}

const Intro = () => {

  const [username, setUserName] = useState("Aryan")
  const [roomID, setRoomID] = useState(1)
  // roomID

  const router = useRouter()
    const [route, setRoute] = useState()
    const handleSubmit = (e) => {
      // useState()
      // useEffect()
      // useRef()
        console.log("Hello")
        e.preventDefault()
        router.push({
            pathname: '/videos/meeting',
            query: {
                name: username,
                id: roomID
             },
        })
  }

  return(
    <div>
        <TextField id="outlined-basic" label="Outlined" variant="outlined" onChange={e => {
            setUserName(e.target.value)
            console.log(username)
          }} />
        <TextField id="outlined-basic" label="Outlined" variant="outlined" onChange={e => {
            setRoomID(e.target.value)
            console.log(roomID)
          }} />
          <Button variant="contained" onChange={e=> handleSubmit(e)} >
            SUBMIT
          </Button>
    </div>
  )
}